source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

target 'Solvr' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sudoku Solver
  pod 'TesseractOCRiOS'
  pod 'OpenCV', '2.4.9.0'

end
